(cl:defpackage flir_lepton_msgs-msg
  (:use )
  (:export
   "<CANDIDATEROIMSG>"
   "CANDIDATEROIMSG"
   "<CANDIDATEROISVECTORMSG>"
   "CANDIDATEROISVECTORMSG"
   "<FLIRLEPTONBATCHMSG>"
   "FLIRLEPTONBATCHMSG"
   "<FLIRLEPTONRAWMSG>"
   "FLIRLEPTONRAWMSG"
   "<GENERALALERTINFO>"
   "GENERALALERTINFO"
   "<TEMPERATURESMSG>"
   "TEMPERATURESMSG"
   "<THERMALALERT>"
   "THERMALALERT"
   "<THERMALALERTVECTOR>"
   "THERMALALERTVECTOR"
  ))

