# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flir_lepton_msgs/ThermalAlertVector.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import flir_lepton_msgs.msg
import std_msgs.msg

class ThermalAlertVector(genpy.Message):
  _md5sum = "bbc179673686a6053173bda4dbac0990"
  _type = "flir_lepton_msgs/ThermalAlertVector"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
ThermalAlert[] alerts

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: flir_lepton_msgs/ThermalAlert
GeneralAlertInfo info

float32 temperature

================================================================================
MSG: flir_lepton_msgs/GeneralAlertInfo
float64 yaw
float64 pitch
float32 probability
"""
  __slots__ = ['header','alerts']
  _slot_types = ['std_msgs/Header','flir_lepton_msgs/ThermalAlert[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,alerts

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ThermalAlertVector, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.alerts is None:
        self.alerts = []
    else:
      self.header = std_msgs.msg.Header()
      self.alerts = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.alerts)
      buff.write(_struct_I.pack(length))
      for val1 in self.alerts:
        _v1 = val1.info
        _x = _v1
        buff.write(_get_struct_2df().pack(_x.yaw, _x.pitch, _x.probability))
        _x = val1.temperature
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.alerts is None:
        self.alerts = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.alerts = []
      for i in range(0, length):
        val1 = flir_lepton_msgs.msg.ThermalAlert()
        _v2 = val1.info
        _x = _v2
        start = end
        end += 20
        (_x.yaw, _x.pitch, _x.probability,) = _get_struct_2df().unpack(str[start:end])
        start = end
        end += 4
        (val1.temperature,) = _get_struct_f().unpack(str[start:end])
        self.alerts.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.alerts)
      buff.write(_struct_I.pack(length))
      for val1 in self.alerts:
        _v3 = val1.info
        _x = _v3
        buff.write(_get_struct_2df().pack(_x.yaw, _x.pitch, _x.probability))
        _x = val1.temperature
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.alerts is None:
        self.alerts = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.alerts = []
      for i in range(0, length):
        val1 = flir_lepton_msgs.msg.ThermalAlert()
        _v4 = val1.info
        _x = _v4
        start = end
        end += 20
        (_x.yaw, _x.pitch, _x.probability,) = _get_struct_2df().unpack(str[start:end])
        start = end
        end += 4
        (val1.temperature,) = _get_struct_f().unpack(str[start:end])
        self.alerts.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2df = None
def _get_struct_2df():
    global _struct_2df
    if _struct_2df is None:
        _struct_2df = struct.Struct("<2df")
    return _struct_2df
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
