# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flir_lepton_msgs/ThermalAlert.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import flir_lepton_msgs.msg

class ThermalAlert(genpy.Message):
  _md5sum = "18245e1dc2e3ca98fa29f3888f3602b3"
  _type = "flir_lepton_msgs/ThermalAlert"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """GeneralAlertInfo info

float32 temperature

================================================================================
MSG: flir_lepton_msgs/GeneralAlertInfo
float64 yaw
float64 pitch
float32 probability
"""
  __slots__ = ['info','temperature']
  _slot_types = ['flir_lepton_msgs/GeneralAlertInfo','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       info,temperature

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ThermalAlert, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.info is None:
        self.info = flir_lepton_msgs.msg.GeneralAlertInfo()
      if self.temperature is None:
        self.temperature = 0.
    else:
      self.info = flir_lepton_msgs.msg.GeneralAlertInfo()
      self.temperature = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d2f().pack(_x.info.yaw, _x.info.pitch, _x.info.probability, _x.temperature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.info is None:
        self.info = flir_lepton_msgs.msg.GeneralAlertInfo()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.info.yaw, _x.info.pitch, _x.info.probability, _x.temperature,) = _get_struct_2d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d2f().pack(_x.info.yaw, _x.info.pitch, _x.info.probability, _x.temperature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.info is None:
        self.info = flir_lepton_msgs.msg.GeneralAlertInfo()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.info.yaw, _x.info.pitch, _x.info.probability, _x.temperature,) = _get_struct_2d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d2f = None
def _get_struct_2d2f():
    global _struct_2d2f
    if _struct_2d2f is None:
        _struct_2d2f = struct.Struct("<2d2f")
    return _struct_2d2f
