// Generated by gencpp from file flir_lepton_msgs/CandidateRoisVectorMsg.msg
// DO NOT EDIT!


#ifndef FLIR_LEPTON_MSGS_MESSAGE_CANDIDATEROISVECTORMSG_H
#define FLIR_LEPTON_MSGS_MESSAGE_CANDIDATEROISVECTORMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <flir_lepton_msgs/CandidateRoiMsg.h>
#include <sensor_msgs/Image.h>

namespace flir_lepton_msgs
{
template <class ContainerAllocator>
struct CandidateRoisVectorMsg_
{
  typedef CandidateRoisVectorMsg_<ContainerAllocator> Type;

  CandidateRoisVectorMsg_()
    : header()
    , candidateRois()
    , image()  {
    }
  CandidateRoisVectorMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , candidateRois(_alloc)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::flir_lepton_msgs::CandidateRoiMsg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::flir_lepton_msgs::CandidateRoiMsg_<ContainerAllocator> >> _candidateRois_type;
  _candidateRois_type candidateRois;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;





  typedef boost::shared_ptr< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CandidateRoisVectorMsg_

typedef ::flir_lepton_msgs::CandidateRoisVectorMsg_<std::allocator<void> > CandidateRoisVectorMsg;

typedef boost::shared_ptr< ::flir_lepton_msgs::CandidateRoisVectorMsg > CandidateRoisVectorMsgPtr;
typedef boost::shared_ptr< ::flir_lepton_msgs::CandidateRoisVectorMsg const> CandidateRoisVectorMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator1> & lhs, const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.candidateRois == rhs.candidateRois &&
    lhs.image == rhs.image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator1> & lhs, const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flir_lepton_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d84a819fbd4af1f20582eeceb6a3e56";
  }

  static const char* value(const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d84a819fbd4af1fULL;
  static const uint64_t static_value2 = 0x20582eeceb6a3e56ULL;
};

template<class ContainerAllocator>
struct DataType< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flir_lepton_msgs/CandidateRoisVectorMsg";
  }

  static const char* value(const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"CandidateRoiMsg[] candidateRois\n"
"\n"
"sensor_msgs/Image image\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: flir_lepton_msgs/CandidateRoiMsg\n"
"Header header\n"
"\n"
"# keypoint.pt.x\n"
"float32 keypointX\n"
"\n"
"# keypoint.pt.y\n"
"float32 keypointY\n"
"\n"
"# bounding box's vertices X coordinate\n"
"float32[] verticesX\n"
"\n"
"# bounding box's vertices Y coordinate\n"
"float32[] verticesY\n"
"\n"
"# blob's outline points X coordinate\n"
"float32[] outlineX\n"
"\n"
"# blob's outline points X coordinate\n"
"float32[] outlineY\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.candidateRois);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CandidateRoisVectorMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flir_lepton_msgs::CandidateRoisVectorMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "candidateRois[]" << std::endl;
    for (size_t i = 0; i < v.candidateRois.size(); ++i)
    {
      s << indent << "  candidateRois[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::flir_lepton_msgs::CandidateRoiMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.candidateRois[i]);
    }
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLIR_LEPTON_MSGS_MESSAGE_CANDIDATEROISVECTORMSG_H
