// Generated by gencpp from file flir_lepton_msgs/FlirLeptonRawMsg.msg
// DO NOT EDIT!


#ifndef FLIR_LEPTON_MSGS_MESSAGE_FLIRLEPTONRAWMSG_H
#define FLIR_LEPTON_MSGS_MESSAGE_FLIRLEPTONRAWMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt16MultiArray.h>

namespace flir_lepton_msgs
{
template <class ContainerAllocator>
struct FlirLeptonRawMsg_
{
  typedef FlirLeptonRawMsg_<ContainerAllocator> Type;

  FlirLeptonRawMsg_()
    : header()
    , rawValues()  {
    }
  FlirLeptonRawMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rawValues(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt16MultiArray_<ContainerAllocator>  _rawValues_type;
  _rawValues_type rawValues;





  typedef boost::shared_ptr< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> const> ConstPtr;

}; // struct FlirLeptonRawMsg_

typedef ::flir_lepton_msgs::FlirLeptonRawMsg_<std::allocator<void> > FlirLeptonRawMsg;

typedef boost::shared_ptr< ::flir_lepton_msgs::FlirLeptonRawMsg > FlirLeptonRawMsgPtr;
typedef boost::shared_ptr< ::flir_lepton_msgs::FlirLeptonRawMsg const> FlirLeptonRawMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator1> & lhs, const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rawValues == rhs.rawValues;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator1> & lhs, const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flir_lepton_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92a43ed64b085feee311b4e58efc17b2";
  }

  static const char* value(const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92a43ed64b085feeULL;
  static const uint64_t static_value2 = 0xe311b4e58efc17b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flir_lepton_msgs/FlirLeptonRawMsg";
  }

  static const char* value(const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# The raw pixel values from the sensor\n"
"std_msgs/UInt16MultiArray rawValues\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint16[]            data        # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rawValues);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlirLeptonRawMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flir_lepton_msgs::FlirLeptonRawMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rawValues: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.rawValues);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLIR_LEPTON_MSGS_MESSAGE_FLIRLEPTONRAWMSG_H
